use crate::platform::SettingsCatalogEntry;

pub(crate) const SETTINGS_CATALOG: &[SettingsCatalogEntry] = &[
    SettingsCatalogEntry {
        title: "General",
        target: "com.apple.systempreferences.GeneralSettings",
        candidate_id_suffix: "com.apple.systempreferences.generalsettings",
        aliases: "settings general about software update storage",
    },
    SettingsCatalogEntry {
        title: "Apple ID",
        target: "com.apple.systempreferences.AppleIDSettings",
        candidate_id_suffix: "com.apple.systempreferences.appleidsettings",
        aliases: "settings apple id icloud media purchases",
    },
    SettingsCatalogEntry {
        title: "iCloud",
        target: "com.apple.systempreferences.AppleIDSettings:icloud",
        candidate_id_suffix: "com.apple.systempreferences.appleidsettings.icloud",
        aliases: "settings icloud cloud drive photos backup hide my email private relay",
    },
    SettingsCatalogEntry {
        title: "Wi-Fi",
        target: "com.apple.wifi-settings-extension",
        candidate_id_suffix: "com.apple.wifi-settings-extension",
        aliases: "settings wifi wireless network internet",
    },
    SettingsCatalogEntry {
        title: "Bluetooth",
        target: "com.apple.BluetoothSettings",
        candidate_id_suffix: "com.apple.bluetoothsettings",
        aliases: "settings bluetooth devices pairing",
    },
    SettingsCatalogEntry {
        title: "Network",
        target: "com.apple.Network-Settings.extension",
        candidate_id_suffix: "com.apple.network-settings.extension",
        aliases: "settings network ethernet dns proxy vpn",
    },
    SettingsCatalogEntry {
        title: "Internet Accounts",
        target: "com.apple.Internet-Accounts-Settings.extension",
        candidate_id_suffix: "com.apple.internet-accounts-settings.extension",
        aliases: "settings internet accounts account google exchange outlook imap icloud",
    },
    SettingsCatalogEntry {
        title: "Sound",
        target: "com.apple.Sound-Settings.extension",
        candidate_id_suffix: "com.apple.sound-settings.extension",
        aliases: "settings sound audio input output volume",
    },
    SettingsCatalogEntry {
        title: "Display",
        target: "com.apple.Displays-Settings.extension",
        candidate_id_suffix: "com.apple.displays-settings.extension",
        aliases: "settings display monitor resolution refresh night shift",
    },
    SettingsCatalogEntry {
        title: "Appearance",
        target: "com.apple.Appearance-Settings.extension",
        candidate_id_suffix: "com.apple.appearance-settings.extension",
        aliases: "settings appearance light dark accent highlight",
    },
    SettingsCatalogEntry {
        title: "Accessibility",
        target: "com.apple.Accessibility-Settings.extension",
        candidate_id_suffix: "com.apple.accessibility-settings.extension",
        aliases: "settings accessibility vision hearing voiceover zoom contrast",
    },
    SettingsCatalogEntry {
        title: "Wallpaper",
        target: "com.apple.Wallpaper-Settings.extension",
        candidate_id_suffix: "com.apple.wallpaper-settings.extension",
        aliases: "settings wallpaper background screen saver",
    },
    SettingsCatalogEntry {
        title: "Screen Saver",
        target: "com.apple.ScreenSaver-Settings.extension",
        candidate_id_suffix: "com.apple.screensaver-settings.extension",
        aliases: "settings screen saver idle lock background",
    },
    SettingsCatalogEntry {
        title: "Desktop & Dock",
        target: "com.apple.Desktop-Settings.extension",
        candidate_id_suffix: "com.apple.desktop-settings.extension",
        aliases: "settings desktop dock menu bar stage manager desk dock",
    },
    SettingsCatalogEntry {
        title: "Screen Time",
        target: "com.apple.Screen-Time-Settings.extension",
        candidate_id_suffix: "com.apple.screen-time-settings.extension",
        aliases: "settings screen time limits downtime",
    },
    SettingsCatalogEntry {
        title: "Focus",
        target: "com.apple.Focus-Settings.extension",
        candidate_id_suffix: "com.apple.focus-settings.extension",
        aliases: "settings focus do not disturb notifications",
    },
    SettingsCatalogEntry {
        title: "Notifications",
        target: "com.apple.Notifications-Settings.extension",
        candidate_id_suffix: "com.apple.notifications-settings.extension",
        aliases: "settings notifications alerts",
    },
    SettingsCatalogEntry {
        title: "Battery",
        target: "com.apple.Battery-Settings.extension",
        candidate_id_suffix: "com.apple.battery-settings.extension",
        aliases: "settings battery power energy",
    },
    SettingsCatalogEntry {
        title: "Lock Screen",
        target: "com.apple.Lock-Screen-Settings.extension",
        candidate_id_suffix: "com.apple.lock-screen-settings.extension",
        aliases: "settings lock screen timeout",
    },
    SettingsCatalogEntry {
        title: "Touch ID & Password",
        target: "com.apple.Touch-ID-Settings.extension",
        candidate_id_suffix: "com.apple.touch-id-settings.extension",
        aliases: "settings touch id password touchid pass fingerprint",
    },
    SettingsCatalogEntry {
        title: "Users & Groups",
        target: "com.apple.Users-Groups-Settings.extension",
        candidate_id_suffix: "com.apple.users-groups-settings.extension",
        aliases: "settings users groups login items accounts user group",
    },
    SettingsCatalogEntry {
        title: "Privacy & Security",
        target: "com.apple.settings.PrivacySecurity.extension",
        candidate_id_suffix: "com.apple.settings.privacysecurity.extension",
        aliases: "settings privacy security permissions firewall",
    },
    SettingsCatalogEntry {
        title: "Control Center",
        target: "com.apple.ControlCenter-Settings.extension",
        candidate_id_suffix: "com.apple.controlcenter-settings.extension",
        aliases: "settings control center menu bar modules",
    },
    SettingsCatalogEntry {
        title: "Siri & Apple Intelligence",
        target: "com.apple.Siri-Settings.extension",
        candidate_id_suffix: "com.apple.siri-settings.extension",
        aliases: "settings siri apple intelligence apple intelligent ai assistant",
    },
    SettingsCatalogEntry {
        title: "Keyboard",
        target: "com.apple.Keyboard-Settings.extension",
        candidate_id_suffix: "com.apple.keyboard-settings.extension",
        aliases: "settings keyboard shortcuts input",
    },
    SettingsCatalogEntry {
        title: "Mouse",
        target: "com.apple.Mouse-Settings.extension",
        candidate_id_suffix: "com.apple.mouse-settings.extension",
        aliases: "settings mouse pointer scrolling click speed",
    },
    SettingsCatalogEntry {
        title: "Trackpad",
        target: "com.apple.Trackpad-Settings.extension",
        candidate_id_suffix: "com.apple.trackpad-settings.extension",
        aliases: "settings trackpad gestures pointer",
    },
    SettingsCatalogEntry {
        title: "Printers & Scanners",
        target: "com.apple.Print-Scan-Settings.extension",
        candidate_id_suffix: "com.apple.print-scan-settings.extension",
        aliases: "settings printers scanners printer scanner airprint",
    },
    SettingsCatalogEntry {
        title: "Wallet & Apple Pay",
        target: "com.apple.WalletSettingsExtension",
        candidate_id_suffix: "com.apple.walletsettingsextension",
        aliases: "settings wallet apple pay cards payments",
    },
    SettingsCatalogEntry {
        title: "Game Center",
        target: "com.apple.Game-Center-Settings.extension",
        candidate_id_suffix: "com.apple.game-center-settings.extension",
        aliases: "settings game center gaming friends",
    },
];
